name: project3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  contained_tab_bar_view: ^0.8.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  primer_progress_bar: ^0.5.0
  simple_shadow: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home_screen_icons/
    - assets/challenges_icons/
    - assets/verbal_skill_icons/
    - assets/profile_icons/
    - google_fonts/
